### ISSUE TITLE
Google SDK unable to read JSON key

### ISSUE THREAD

**Issue by craigdbarber** [jenkinsci/google-oauth-plugin#35] opened 2019-03-08 01:00 UTC
I am trying to execute gcloud commands using GCloud sdk plugin. But I am getting an error ERROR: (*gcloud.auth.activate-service-account) Could not read* json file. Can someone help me out on this? Thanks in advance.

**Comment by craigatgoogle** [comment] 2019-03-08 01:00
Migrated from: https://issues.jenkins-ci.org/browse/JENKINS-46614

**Comment by stephenashank** [comment] 2019-09-24 20:30
duplicate of #6

**Closed by stephenashank** 2019-09-24 20:30 UTC
Labels: bug
