### ISSUE TITLE
Store a stable unique ID for each credential

### ISSUE THREAD

**Issue by craigdbarber** [jenkinsci/google-oauth-plugin#42] opened 2019-03-08 01:07 UTC
Currently the "project name" is the only way to refer to a credential, e.g. via GoogleRobotCredentials.getById(projectName);

However as this is a free text field, users can rename the credential, and jobs configured to use that credential (having stored the "project name" value, aka "id" in the job config) will no longer work.

Other credential types seem to use the id field to store a stable UUID value (which isn't shown to the user), e.g.
https://github.com/jenkinsci/credentials-plugin/blob/a6c40a1/src/main/java/com/cloudbees/plugins/credentials/impl/BaseStandardCredentials.java#L73

So it seems like id here should really be projectName — it would be nice if this plugin used the id field in the same way as other credential plugins.

**Comment by craigatgoogle** [comment] 2019-03-08 01:08
Migrated from: https://issues.jenkins-ci.org/browse/JENKINS-29018

**Comment by stephenashank** [comment] 2019-09-24 20:40
Closing as duplicate of #12, this will be tracked there.

**Closed by stephenashank** 2019-09-24 20:40 UTC
Labels: duplicate
